from pydantic import BaseModel

class PredictRequest(BaseModel):
    ds: str
    is_weekend: int
    is_halloween: int
    dayofweek_1: int
    dayofweek_2: int
    dayofweek_3: int
    dayofweek_4: int
    dayofweek_5: int
    dayofweek_6: int
    dayofweek_7: int
    month_1: int
    month_2: int
    month_3: int
    month_4: int
    month_5: int
    month_6: int
    month_7: int
    month_8: int
    month_9: int
    month_10: int
    month_11: int
    month_12: int
    hour_1: int
    hour_2: int
    hour_3: int
    hour_4: int
    hour_5: int
    hour_6: int
    hour_7: int
    hour_8: int
    hour_9: int
    hour_10: int
    hour_11: int
    hour_12: int
    hour_13: int
    hour_14: int
    hour_15: int
    hour_16: int
    hour_17: int
    hour_18: int
    hour_19: int
    hour_20: int
    hour_21: int
    hour_22: int
    hour_23: int
    hour_24: int